### ISSUE TITLE
Comando de script

### ISSUE THREAD

**Issue by viniciusn** [Cronus-Emulator/Cronus#21]
Como usar o comando de script getcartinventorylist ? não tem exemplo na documentação :(

**Comment by SlexFire** [comment]
Estamos organizando, é que a documentação é muito grande. Eu posso te explicar por aqui se quiser.

**Comment by viniciusn** [comment]
Perdão, o que aconteceu é que eu tinha baixado uma versão antiga do cronus que não tinha o comando, mas eu adicionei e consegui usar, esqueci de fechar a issue.

**Comment by SlexFire** [comment]
Ok, disponha sempre.
