### ISSUE TITLE
Bug com teletransporte e posição da saida Izlude

### ISSUE THREAD

**Issue by AchcarLucas** [Cronus-Emulator/Cronus#30]
Bom, estou aqui para informar um problema no mapa de izlude, estou usando um Hexed 2014-03-05b, e o teletransporte de izlude parece que está errado.

Segue as imagens

http://s10.postimg.org/z1s05o947/nao_se_move.png
http://s10.postimg.org/mklciidyf/Portal_Errado.png

nao_se_move.png: Não consigo se movimentar nessa área.

Aqui foi na hora de entrar em izlude, ele me leva para o meio do mar, ocorreu isso também em um outro teleporte, quando você cria seu personagem, inclusive com alguns NPCs submersos, irei tentar tirar umas screenshot desses problemas também.

Além disso, desse ponto em diante não se pode chegar até o portal, pois o personagem não se move mais.

http://s10.postimg.org/v44qg9mav/Dois.png

************ Edit ***************

Aqui está o bug com o mapa iz_int 96,79
Ele está me teletransportando para esse local:

http://s23.postimg.org/t0pea2f6h/Porta_Zuado.png

Inclusive possui NPC em baixo d'água.

http://s23.postimg.org/f8azefoez/Problema2.png

**Comment by Linnesz** [comment]
Baixe o novo mapa de izlude e substitua-o em seu emulador !
