### ISSUE TITLE
Erro ao compilar no Windows via clang

### ISSUE THREAD

**Issue by joaopauloCODE** [Cronus-Emulator/Cronus#31]
Olá, sempre faço o mesmo procedimento para compilar.
- Copiar a pasta clang para a C:\;
- Ativar via Cronus.bat contido no mesma pasta;
- Iniciar o Cronus.bat do Emulador);

Mas quando fui compilar para realizar um teste aqui, apresentou o seguinte erro que esta na imagem:
![screenshot_49](https://cloud.githubusercontent.com/assets/15686989/14476935/24891e60-00e1-11e6-9ee1-51f8ce735168.png)
Image Link Mirror: http://prntscr.com/arioyp

Obrigado pela paciência.

**Comment by SlexFire** [comment]
Olá!
Atualmente o cronus não está compatível com o clang, por favor veja o tutorial abaixo para conseguir compilar:

http://forum.cronus-emulator.com/topic/153889-compilando-cronus-2016/

**Comment by SlexFire** [comment]
Por falta de resposta, entende-se que o problema foi resolvido!
