### ISSUE TITLE
BUG db emulador.

### ISSUE THREAD

**Issue by Mihaelll** [Cronus-Emulator/Cronus#32]
Pessoal eu notei uma coisa aqui, tava testando o emulador e percebi que ele não está lendo a item_db.conf da pasta re. Compilei o emulador e tentei criar um todos itens do arquivo e nenhum existe. O Emulador está lendo somente a pasta pre-re e a item_db2.conf da pasta db normal.

Deem uma olhada nisso ai fazendo o favor :/

**Comment by SlexFire** [comment]
Obg por reportar, Mihaell, vamos dar uma verificada e te dar um retorno por aqui.

**Comment by Mihaelll** [comment]
De nada slex <3

**Comment by SlexFire** [comment]
@Mihaelll  qual versão de client você está usando?

**Comment by Mihaelll** [comment]
2014 03 05

**Comment by SlexFire** [comment]
@Mihaelll , desculpa a demora. Bem, efetuei testes com a última revisão do Cronus e obtive êxito. testes:

- Erros propositais (Sendo mostrados pelo map-server)
- Criação de Item (Reconhecendo a criação normal)
- Testes similares aos citados anteriormente
- **Conclusão:** Está funcionando normal

Existe algum caso específico que você queira que eu teste?

**Comment by SlexFire** [comment]
Foram realizados vários testes e todos apresentaram o funcionamento comum. Qualquer outro caso, favor reportar imediatamente para que o problema seja verificado.
