### ISSUE TITLE
Lvl Max

### ISSUE THREAD

**Issue by J4ND3RS0N** [Cronus-Emulator/Cronus#33]
Não estou conseguindo alterar o nível max no servidor, alterei o Max_Level no mmo.h mas ainda assim não foi possível chegar ao nível que eu configurei, e sim eu compilei e não teve erros.

Vir em outro emulador que tem essas linhas no mmo.h, mas no cronus não achei as mesmas!

// Tabela de Nível Máximo por Classes
enum _max_level_ {
/// Nível Max. de Base - Suporta até nível de base 1000
	BASE_MAX_1LV	= 99,	// Classes Normais e Classes Baby.
	BASE_MAX_2LV	= 99,	// Classes Transcedentais.
	BASE_MAX_3LV	= 175,	// Terceira Classe Normal, Terceira Classe Bebê.
	BASE_MAX_4LV	= 160,	// Super Aprendiz Expandido e Kagerou/Oboro.
/// Nível Max. de Classe - Suporta até nível de classe 255
	JOB_MAX_1LV		= 10,	// Aprendiz & Bebê Aprendiz.
	JOB_MAX_2LV		= 50,	// Primeira Classe & Primeira Classe Bebê.
	JOB_MAX_3LV		= 50,	// Segunda Classe & Segunda Classe Bebê.
	JOB_MAX_4LV		= 10,	// Aprendiz Transcedental.
	JOB_MAX_5LV		= 50,	// Primeira Classe Transcedental.
	JOB_MAX_6LV		= 70,	// Segunda Classe Transcedental.
	JOB_MAX_7LV		= 60,	// Terceira Classe, Terceira Classe Bebê.
	JOB_MAX_8LV		= 50,	// Super Aprendiz Expandido e Kagerou/Oboro.
	JOB_MAX_9LV		= 70,	// Ninja/Gunslinger.
	JOB_MAX_10LV	= 50,	// Taekwon.
	JOB_MAX_11LV	= 50,	// Mestre Taekwon.
	JOB_MAX_12LV	= 50,	// Espiritualista.
	JOB_MAX_13LV	= 99,	// Super Aprendiz & Bebê Super Aprendiz.
};

**Comment by SlexFire** [comment]
@J4ND3RS0N , por favor abra um tópico em nosso fórum, aqui é apenas para bugs/erros.

De toda forma em mmo.h veja e altere: #define MAX_LEVEL 175
Depois vá em db/re ou db/pre-re (De acordo com sua configuração) e altera o arquivo exp.txt.
