### ISSUE TITLE
Problema com o Fórum

### ISSUE THREAD

**Issue by alexandrebfaust** [Cronus-Emulator/Cronus#34]
_Estou tentando acessar o fórum, porém o template não está carregando nem o conteúdo, já testei em vários pcs._ 

Estou na dúvida de como faço para compilar o servidor

http://forum.cronus-emulator.com/

**Comment by SlexFire** [comment]
Olá @alexandrebfaust ! Esta área é apenas para reportar bugs no emulador ok? Mas vou tentar te ajudar, veja esse tutorial e siga atenciosamente cada passo:
https://www.youtube.com/watch?v=ol179ybDmXM

Qualquer dúvida, abra um tópico no fórum que lhe responderei o mais breve possível. Sucesso aew!
