### ISSUE TITLE
Problema tabela login

### ISSUE THREAD

**Issue by Cainho** [Cronus-Emulator/Cronus#35]
Boa noite, hoje eu estava fazendo alguns testes aqui no meu pc e notei ao tentar realizar um cadastro utilizando um código que eu estou escrevendo que ele estava dando erro na coluna 'lastlogin' ao tentar registrar, fala que o formato datetime para esta coluna está incorreto.
Não testei de outra maneira ainda para ver se também ocorre este erro, apenas usei o mesmo script nas tabelas do hercules e o problema não ocorreu.

**Comment by SlexFire** [comment]
Olá @Cainho, tudo bem? 
Fiz um teste simples aqui e a inserção deu certo! Como é que está sendo realizado este processo para que eu possa testar?

**A saber:** Desde o começo das traduções não estamos mais seguindo o Hércules, estamos nos organizando para seguir de forma independente, porém, até chegar o desenvolvimento de fato, a tradução dos scripts terá de ser concluída. Até lá, farei apenas algumas coisas em paralelo, mas dando prioridade aos bugs reportados!

Obg por reportar!

**Comment by Cainho** [comment]
Ah entendi, não sabia que não estavam mais seguindo a base deles.
Bom eu usei um script em php orientado a objetos, cadastrando na coluna userid, user_pass, email, sex e birthdate, eu envio os todos os dados normalmente para a classe e quando vai executar o insert acusa erro na coluna lastlogin, caso não encontrar nada eu posso te mandar por PM o script que eu estou usando para que você possa testar.

**Comment by SlexFire** [comment]
Humm, verifiquei e não encontrei problemas! Me manda por PM no fórum que eu testo e te dou um feedback. Estou no aguardo!

**Comment by SlexFire** [comment]
Conclusão: Foram feitos testes de acordo com o erro reportado e não foi encontrado nenhum erro. Qualquer observação favor reportar, agradecido!
