### ISSUE TITLE
Danças Bardo

### ISSUE THREAD

**Issue by Cainho** [Cronus-Emulator/Cronus#48]
Testando o emulador com a pré-renovação ativada percebi que as danças do Bardo não funcionam, passo por dentro do efeito da habilidade porém nenhum status é concedido ao jogador, testei com crepusculo sangrento e poema de bragi e nenhum dos dois funcionou.
Não testei com a renovação ativada, fiz o teste com o emulador sem alterações e o problema persiste.

**Comment by SlexFire** [comment]
Ok @Cainho muito obg por reportar, farei testes e te passo um retorno..

**Comment by Cainho** [comment]
OK, estou no aguardo.

**Comment by SlexFire** [comment]
Foram efetuados testes e as habilidades estão conforme as descrições, portanto as skills estão corretas.

**Comment by Cainho** [comment]
Ok, também foi um erro meu. Fiz uma confusão nos efeitos que as habilidades aplicavam.
Vlw.

**Comment by SlexFire** [comment]
Blz! Todavia obrigado por reportar.
