### ISSUE TITLE
sp 1 acima de 150

### ISSUE THREAD

**Issue by jarlano** [Cronus-Emulator/Cronus#49]
Olá, a classe rebelion fica com sp 30 como sp máximo ao upar acima de 150 de baselvl. Favor gostaria de uma resposta de como corrigir. Obrigado.

**Comment by jarlano** [comment]
email:jarlano.santos@gmail.com

**Comment by SlexFire** [comment]
Já estamos analisando isso @jarlano !

**Comment by SlexFire** [comment]
@jarlano testa com a ultima revisão do Cronus.

**Comment by SlexFire** [comment]
Problema corrigido na revisão: https://github.com/Cronus-Emulator/Cronus/commit/2fa7ba345948847a650b9a5d78d819c044060548

**Comment by jarlano** [comment]
Sobre a questão do código fonte das skills do rebelion, Tem previsão?
