### ISSUE TITLE
Contas _M / _F não são registradas

### ISSUE THREAD

**Issue by Iniciando** [Cronus-Emulator/Cronus#50]
Não conseguil criar mais de duas contas usando o _m / _f. Então fui testar e realmente houve esse problema em outro emulador , que só foi resolvido com uma atualização. 

http://forum.brathena.org/index.php/tracker/issue-58-contas-m-f-nao-sao-registradas/

**Comment by Spell-Master** [comment]
O funcionamento da função está normal. Pois assim que usamos o emulador todo santo dia para testes

**Comment by Iniciando** [comment]
Vc criou mais de 2 contas pelo cliente? só tive problemas após as 2.

**Comment by Spell-Master** [comment]
Refeito o teste com novo banco de dados do zero criei 5 contas usando _m e 5 contas com _f 5 ambas foram realizados login nas contas e o funcionamento está normal.
