### ISSUE TITLE
Habilidades de 2º classe, sendo utilizado antes das habilidade de 1º classe

### ISSUE THREAD

**Issue by Iniciando** [Cronus-Emulator/Cronus#51]
Estava utilizando a ultima versão do emulador, e após utilizar o reset de habilidades, notei que as habilidades das 2º classes, estavam sendo utilizado antes das habilidade de 1º classe, e isso é errado. Deve-se utilizar as habilidades em uma determinada ordem após o reset.
1º Habilidades básicas - 9 pontos
2º           -         1ºclasse - 39 a 49 pontos
3º           -         2º classe - 69 pontos
4º           -         3º classe - 59 pontos

**Comment by Spell-Master** [comment]
Vou analisar.

**Comment by Spell-Master** [comment]
Testes realizados:
Através do resetskill (comando de script) e @skreset (Comando de jogador)
Aprendiz a 2º classe. Resultado: Nenhuma anomalia detectada.
Aprendiz T a 2º Classe T. Resultado: Nenhuma anomalia detectada.
Aprendiz a 3º Classe. Resultado: Nenhuma anomalia detectada.
Aprendiz T a 3º Classe T. Resultado: Nenhuma anomalia detectada.

Alguns outros teste foram realizados em busca de causar o suposto bug, depois de algum tempo chegado ao erro por 2 etapas diferentes.
Má configuração player_skillup_limit
Má configuração do SkillTreeView.lub

Resultado final (Não há erro com o emulador)
