### ISSUE TITLE
Nao compila/liga em linux centos 6/7

### ISSUE THREAD

**Issue by julinhobrow** [Cronus-Emulator/Cronus#53]
Conforme a descrição era pra o emulador compilar com GCC 4.8+ ou clang 3.8+ porem ao tentar fazer a compilação com eles na hora de ligar so aparecia a mensagem nohup tente com a devtools-4 também que é a mais recente do centos e nada. Acredito ser no make SQL o problema já que causa muitos warnings detalhe a mysql-devel instalada foi a MySQL 5.1 tentei a da mysql 5.5 e a da mariadb 5.5 ja com mariadb 10.0 e 10.1 nao rodou o make sql

**Comment by SlexFire** [comment]
@julinhobrow eu compilo ele numa boa em linux...! Os Warnings irei corrigir numa atualização futura, na qual estou trabalhando!

**Comment by julinhobrow** [comment]
pois só aparece nohup na hora de ligar em ambos os centos a pergunta no caso é qual compilador?

**Comment by SlexFire** [comment]
Vou instalar o CentOS numa VM aqui pra testar nesses próximos dias. Testei em Debian e funcionou perfeitamente, liguei o emulador e entrei no jogo normalmente.

**Comment by SlexFire** [comment]
@julinhobrow detectei o problema e está no Cronus commander! Vou verificar e corrigir!

**Comment by julinhobrow** [comment]
que bom to com servidor pronto pra migrar do hercules pra ele.

**Comment by SlexFire** [comment]
@julinhobrow aí sim hein!

**Comment by julinhobrow** [comment]
me avisa quando corrigir porque achei que você já tinha ajeitado rs.

**Comment by julinhobrow** [comment]
Voltei pra adicionar mais linux na lista não starta em ubuntu 14.04, Debian 7, SUSE 42, Arch, Fedora 25, Funcionou em Debian 8 e Ubuntu 16.04 mais eu gostaria de usar em centos.
