### ISSUE TITLE
Habilidade de Mecânico Artilharia Arcana não ativa.

### ISSUE THREAD

**Issue by iamferreirajp** [Cronus-Emulator/Cronus#54]
A habilidade Artilharia Caçadora funciona perfeitamente, porém a habilidade artilharia arcana não ativa. Ela até consome os brigans e ferros quando é utilizada, mas só aparece "Habilidade falhou" no chat e ela não é ativada.

**Comment by SlexFire** [comment]
Obrigado mais uma vez por reportar @iamferreirajp vou juntar com as verificações que farei amanhã.

**Comment by iamferreirajp** [comment]
Sem problemas @SlexFire espero um dia poder contribuir como você e não deixar morrer a ideia.

**Comment by SlexFire** [comment]
@iamferreirajp vou verificar hoje a noite, desculpa a demora é pq estou meio sobrecarregado com umas coisas do trabalho, mas postarei um retorno hoje.

**Comment by SlexFire** [comment]
@iamferreirajp já identifiquei o problema, estarei postando a correção nos próximos commits!

**Comment by SlexFire** [comment]
@iamferreirajp desculpa a demora! Por conta do trabalho e problemas pessoais, acabei esquecendo completamente. Commitei a correção da skill, qualquer coisa é só informar.

Link do commit:
https://github.com/Cronus-Emulator/Cronus/commit/af3cd4da9c6d69941c2bc43d1547985500e64b67
