### ISSUE TITLE
ainda não entedi como ajeitar olha o erro.

### ISSUE THREAD

**Issue by julinhobrow** [Cronus-Emulator/Cronus#57]
[Aviso]: npc_parsename: Nome unico duplicado no arquivo 'npc/comerciantes/Lojas.txt', linha '1018'. Renomeando 'Feirante#lhz' para '1_482_124_129'.
[Depurar]: este npc:
   nome de exibicao 'Feirante#lhz'
   nome unico 'Feirante#lhz'
   mapa=lighthalzen, x=124, y=129
[Depurar]: outro npc 'npc/comerciantes/Lojas.txt' :
   nome de exibicao 'Feirante#lhz'
   nome unico 'Feirante#lhz'
   mapa=lighthalzen, x=69, y=75
[Aviso]: npc_parsename: Nome unico duplicado no arquivo 'npc/comerciantes/Lojas.txt', linha '1107'. Renomeando 'Feirante#lhz2' para '1_484_21_220'.
[Depurar]: este npc:
   nome de exibicao 'Feirante#lhz2'
   nome unico 'Feirante#lhz2'
   mapa=lhz_in02, x=21, y=220
[Depurar]: outro npc 'npc/comerciantes/Lojas.txt' :
   nome de exibicao 'Feirante#lhz2'
   nome unico 'Feirante#lhz2'
   mapa=lhz_in02, x=17, y=220
[Aviso]: npc_parsename: Nome unico duplicado no arquivo 'npc/comerciantes/Lojas.txt', linha '1715'. Renomeando 'Florista#prt' para '1_171_113_42'.
[Depurar]: este npc:
   nome de exibicao 'Florista#prt'
   nome unico 'Florista#prt'
   mapa=prontera, x=113, y=42
[Depurar]: outro npc 'npc/comerciantes/Lojas.txt' :
   nome de exibicao 'Florista#prt'
   nome unico 'Florista#prt'
   mapa=prontera, x=58, y=182
[Aviso]: npc_parsename: Nome unico duplicado no arquivo 'npc/comerciantes/Lojas.txt', linha '1761'. Renomeando 'Feirante#prt' para '1_171_48_58'.
[Depurar]: este npc:
   nome de exibicao 'Feirante#prt'
   nome unico 'Feirante#prt'
   mapa=prontera, x=48, y=58
[Depurar]: outro npc 'npc/comerciantes/Lojas.txt' :
   nome de exibicao 'Feirante#prt'
   nome unico 'Feirante#prt'
   mapa=prontera, x=104, y=49
[Aviso]: npc_parsename: Nome unico duplicado no arquivo 'npc/comerciantes/Lojas.txt', linha '1951'. Renomeando 'Feirante#ra' para '1_560_65_80'.
[Depurar]: este npc:
   nome de exibicao 'Feirante#ra'
   nome unico 'Feirante#ra'
   mapa=rachel, x=65, y=80
[Depurar]: outro npc 'npc/comerciantes/Lojas.txt' :
   nome de exibicao 'Feirante#ra'
   nome unico 'Feirante#ra'
   mapa=ra_in01, x=254, y=300
[Aviso]: npc_parsename: Nome unico duplicado no arquivo 'npc/comerciantes/Seiyablem.txt', linha '331'. Renomeando 'Jovem#moc' para '1_120_60_42'.
[Depurar]: este npc:
   nome de exibicao 'Jovem#moc'
   nome unico 'Jovem#moc'
   mapa=morocc, x=60, y=42
[Depurar]: outro npc 'npc/cidades/morocc.txt' :
   nome de exibicao 'Jovem#moc'
   nome unico 'Jovem#moc'
   mapa=moc_ruins, x=132, y=144
[Aviso]: npc_parsename: Nome unico duplicado no arquivo 'npc/quests/cidades/Payon.txt', linha '153'. Renomeando 'Jovem#pay' para '1_436_25_71'.
[Depurar]: este npc:
   nome de exibicao 'Jovem#pay'
   nome unico 'Jovem#pay'
   mapa=payon_in02, x=25, y=71
[Depurar]: outro npc 'npc/comerciantes/Seiyablem.txt' :
   nome de exibicao 'Jovem#pay'
   nome unico 'Jovem#pay'
   mapa=payon, x=143, y=143

**Comment by SlexFire** [comment]
Vou olhar agora o que está havendo...!

**Comment by Spell-Master** [comment]
Isso foi devido a última tradução feita. Estarei ajeitando isso ainda hoje.

**Comment by SlexFire** [comment]
Nomes duplicados

**Comment by SlexFire** [comment]
@Spell-Master @julinhobrow já corrigi, vou ver aqui só uma coisa.

**Comment by Spell-Master** [comment]
Acabei de empurrar a correção
