### ISSUE TITLE
GD_ITEMEMERGENCYCALL

### ISSUE THREAD

**Issue by Likeeit** [Cronus-Emulator/Cronus#60]
Atualmente a forma oficial não funciona, há uma habilidade para isso.

GD_ITEMEMERGENCYCALL

Http: //ratemyserver....b&item_id=12968
Http: //ratemyserver....b&item_id=12969
Http: //ratemyserver....b&item_ID=12970
     
Parece que já tinha sido adicionado ao Hercules e foi perdido na troca de emulador. Referência # 534
Tópico aberto em Jul 17 2013: http://herc.ws/board/topic/1584-implement-new-skill-gd/

**Comment by SlexFire** [comment]
@Likeeit vamos analisar. Obg por reportar!

**Comment by SlexFire** [comment]
@Likeeit depois você testa e me fala se deu certo, mas acredito que está conforme sua informação. Se faltar alguma coisa você informa.
