### ISSUE TITLE
Link de download do compilador Windows quebrado

### ISSUE THREAD

**Issue by ediejohnny** [Cronus-Emulator/Cronus#80]
O link do README do GitHub para baixar o compilador do servidor para Windows está quebrado.

**Comment by Spell-Master** [comment]
Use esse: https://mega.nz/file/XYdxyZiY#K0zcnNIvgNBVGIfbQ8v5zYjhGM8NoVLxjNFrMYBvkSg
Aliás use outro emulador

**Comment by ediejohnny** [comment]
Por que usar outro emulador? Existe outro brasileiro?
