### ISSUE TITLE
Meu homunculus não solta capricho

### ISSUE THREAD

**Issue by piraforce** [Cronus-Emulator/Cronus#82]
Galera, to tendo um problema com o homunculus vanil em meu server, ele nao usa capricho quando ordeno, e não e por falta de SP ou cool down ele literalmente não usa msm e não faço ideia do pq, se alguém souber agradeceria mt

**Comment by elanosilveira** [comment]
rathena.org 

Esse repositório está desatualizado apenas 6 anos.

**Comment by piraforce** [comment]
Puts, mas n tem como ajeitar? O hexed até diz onde é o erro mas n consigo descobri o q significa o que ele me diz

**Comment by GMouraP** [comment]
Ter como tem, o problema é o que o @elanosilveira disse, o repositorio está bem desatualizado, quase abandonado, talvez compense mais pra voce trocar pro rathena que está sendo mantido do que insistir no Cronus, infelizmente.

**Comment by piraforce** [comment]
Ah sim entendi, o Cronus realmente ta complicado, acho que até o site já morreu,  enfim... Obrigado @GMouraP e @elanosilveira vou procurar me atualizar manos
